#!/usr/bin/env bash

docker run --rm\
  -e GITHUB_USER=change \
  -e GITHUB_REPO=change \
  -e GITHUB_BRANCH=change \
  -e GITHUB_TOKEN=change \
  -e FORCE_COLOR=1 \
  -v `pwd`/report:/container/workspace/repocitory-code/test/report \
  madoos/node-test-builder:caseonit
